/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.genereated.retailer;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProductFilterType implements org.apache.thrift.TEnum {
  PRICE(0),
  REVIEW_RATINGS(1);

  private final int value;

  private ProductFilterType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProductFilterType findByValue(int value) { 
    switch (value) {
      case 0:
        return PRICE;
      case 1:
        return REVIEW_RATINGS;
      default:
        return null;
    }
  }
}
