/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.genereated.retailer;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class retailerConstants {

  public static final Map<Integer,List<Integer>> RETAILER_SERVER_PORT = new HashMap<Integer,List<Integer>>();
  static {
    List<Integer> tmp68 = new ArrayList<Integer>();
    tmp68.add(28001);
    tmp68.add(28001);

    RETAILER_SERVER_PORT.put(1, tmp68);
    List<Integer> tmp69 = new ArrayList<Integer>();
    tmp69.add(28002);
    tmp69.add(28002);

    RETAILER_SERVER_PORT.put(2, tmp69);
    List<Integer> tmp70 = new ArrayList<Integer>();
    tmp70.add(28003);
    tmp70.add(28003);

    RETAILER_SERVER_PORT.put(3, tmp70);
    List<Integer> tmp71 = new ArrayList<Integer>();
    tmp71.add(28004);
    tmp71.add(28004);

    RETAILER_SERVER_PORT.put(4, tmp71);
    List<Integer> tmp72 = new ArrayList<Integer>();
    tmp72.add(28005);
    tmp72.add(28005);

    RETAILER_SERVER_PORT.put(5, tmp72);
    List<Integer> tmp73 = new ArrayList<Integer>();
    tmp73.add(28006);
    tmp73.add(28006);

    RETAILER_SERVER_PORT.put(6, tmp73);
  }

  public static final Map<String,Integer> RETAILERS = new HashMap<String,Integer>();
  static {
    RETAILERS.put("bananarepublic", 1);
    RETAILERS.put("bjs", 1);
    RETAILERS.put("bestbuy", 1);
    RETAILERS.put("costco", 1);
    RETAILERS.put("cvs", 1);
    RETAILERS.put("gap", 1);
    RETAILERS.put("homedepot", 1);
    RETAILERS.put("jcpenny", 1);
    RETAILERS.put("testretailer", 1);
    RETAILERS.put("kohls", 2);
    RETAILERS.put("lowes", 2);
    RETAILERS.put("macys", 2);
    RETAILERS.put("nordstrom", 2);
    RETAILERS.put("oldnavy", 2);
    RETAILERS.put("riteaid", 2);
    RETAILERS.put("sears", 2);
    RETAILERS.put("samsclub", 2);
    RETAILERS.put("staples", 2);
    RETAILERS.put("walgreens", 2);
    RETAILERS.put("testretailer2", 2);
    RETAILERS.put("walmart", 3);
    RETAILERS.put("target", 4);
    RETAILERS.put("amazon", 5);
    RETAILERS.put("amazonbs", 5);
    RETAILERS.put("babysrus", 6);
    RETAILERS.put("toysrus", 6);
  }

}
