drop table GENERIC_PRODUCT;
CREATE table GENERIC_PRODUCT
( 
	GENERIC_PRODUCT_ID VARCHAR(20) NOT NULL,
	GENERIC_PRODUCT_NAME VARCHAR(20) NOT NULL,
	ACTIVE  CHAR(1) NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,

	PRIMARY KEY USING HASH (GENERIC_PRODUCT_ID)
	
) ENGINE=InnoDB;
describe GENERIC_PRODUCT;