drop table  GENERIC_CATEGORY;
CREATE table GENERIC_CATEGORY
( 
	GENERIC_CATEGORY_ID VARCHAR(20) NOT NULL,
	GENERIC_CATEGORY_NAME VARCHAR(20) NOT NULL,
	ACTIVE  CHAR(1) NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,

	PRIMARY KEY USING HASH (GENERIC_CATEGORY_ID)
	
) ENGINE=InnoDB;
describe GENERIC_CATEGORY;