USE PRODUCTS;
DROP TABLE IF EXISTS PRICE_ALERT_HISTORY;

CREATE TABLE PRICE_ALERT_HISTORY
(
	ALERT_HISTORY_ID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	ALERT_ID INTEGER(8) UNSIGNED NOT NULL,
	TIME_SENT DATETIME NOT NULL,
	NOTIFICATION_PRICE FLOAT NOT NULL,
	
	PRIMARY KEY USING BTREE (ALERT_HISTORY_ID)
) ENGINE=MYISAM;
describe PRICE_ALERT_HISTORY;