USE PRODUCTS;
/*
This table is used to store the downloaded products. After the products have been vetted,
the products are moved into the PRODUCT table and the price history is moved into
PRODUCT_PRICE_HISTORY table.
*/

##NOTE: auto_incrememet is used here as we take cut of production table
#every month and create new one which starts with given ID
CREATE table PRODUCT_DOWNLOAD
(	
	ID BIGINT NOT NULL AUTO_INCREMENT KEY,
	RETAILER_ID VARCHAR(20) NOT NULL,
	CATEGORY_ID INTEGER NOT NULL,
	PRODUCT_NAME VARCHAR(300) NOT NULL,
	DOWNLOAD_TIME DATETIME NOT NULL,			
	MODEL_NO VARCHAR(100),
	DESCRIPTION VARCHAR(5000),
	IMAGE_URL VARCHAR(500),
	URL VARCHAR(500),
	PRICE FLOAT NOT NULL,
	PROCESSED VARCHAR(1) NOT NULL DEFAULT '0',
	RECON_SUCCESS VARCHAR(1),
	RECON_TEXT VARCHAR(200),
	MODE varchar(1) NOT NULL DEFAULT 'A',
	REVIEW_RATING DECIMAL(4,2) NOT NULL,
	NUM_REVIEWS DECIMAL(6) NOT NULL,
	BEST_SELLER_RANK DECIMAL(8) NOT NULL,
	INDEX DOWNLOAD_TIME_idx using BTREE (DOWNLOAD_TIME)
) ENGINE=MyISAM, AUTO_INCREMENT=1448357073;
describe PRODUCT_DOWNLOAD;


create database PRODUCTS_ARCHIEVE;

RENAME TABLE PRODUCTS.PRODUCT_DOWNLOAD TO PRODUCTS_ARCHIEVE.PRODUCT_DOWNLOAD_<20130330>;

select max(ID) from PRODUCTS_ARCHIEVE.PRODUCT_DOWNLOAD;

set AUTO_INCREMENT=ABOVE_ID+1 in the create table

select * from PRODUCT_DOWLOAD where ID>=978611001 INTO OUTFILE 'PRODUCT_DOWLOAD_TEMP.20130330';



select max(ID) from PRODUCT_DOWNLOAD;

RENAME TABLE PRODUCTS.PRODUCT_DOWNLOAD TO PRODUCTS_ARCHIEVE.PRODUCT_DOWNLOAD_20130608;


set AUTO_INCREMENT=ABOVE_ID+1 in the create table

select * from LAST_PROCESSED;

INSERT INTO PRODUCT_DOWNLOAD SELECT * FROM PRODUCTS_ARCHIEVE.PRODUCT_DOWNLOAD_20130608 WHERE ID>1446647345

DELETE FROM PRODUCTS_ARCHIEVE.PRODUCT_DOWNLOAD_20130608 WHERE ID>1446647345 LIMIT 1000000
-go on both boxes and zip new archive table

#select * from PRODUCT_DOWLOAD where ID>=978611001 INTO OUTFILE 'PRODUCT_DOWLOAD_TEMP.20130330';
 