use PRODUCTS

CREATE table PRODUCT_SELL_RANKS_HISTORY
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	RANK DECIMAL(8) NOT NULL,
	END_TIME DATETIME, 
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID),
	INDEX TIME_idx using BTREE (TIME)
	
) ENGINE=MYISAM;
describe PRODUCT_SELL_RANKS_HISTORY;

#ALTER TABLE PRODUCT_SELL_RANKS_HISTORY DROP COLUMN RETAILER_ID;