USE PRODUCTS
DROP TABLE IF EXISTS PRODUCT;
/*
There could be two products in the same category with same product name but different price/url. Url should
always be unique
*/
CREATE table PRODUCT
( 	
	PRODUCT_ID INTEGER(8) UNSIGNED NOT NULL,
	PRODUCT_NAME VARCHAR(300) NOT NULL,
	CATEGORY_ID INTEGER NOT NULL,
	RETAILER_ID VARCHAR(20) NOT NULL,		
	GENERIC_PRODUCT_ID VARCHAR(20) NOT NULL,
	MODEL_NO VARCHAR(100),		
	DESCRIPTION VARCHAR(5000),
	IMAGE BLOB,
	IMAGE_URL VARCHAR(500) NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME,
	URL VARCHAR(500) NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,
	
	PRIMARY KEY USING BTREE (PRODUCT_ID),	 
	CONSTRAINT UNIQUE KEY UNIQ_PROD_KEY USING BTREE (PRODUCT_NAME, CATEGORY_ID, RETAILER_ID),		
	INDEX GENERIC_PRODUCT_ID_idx using BTREE (GENERIC_PRODUCT_ID),
	INDEX CATEGORY_ID_idx using BTREE (CATEGORY_ID),
	INDEX RETAILER_ID_idx using BTREE (RETAILER_ID),
	INDEX PRODUCT_NAME_idx using BTREE (PRODUCT_NAME)
) ENGINE=InnoDB;
describe PRODUCT;