USE PRODUCTS
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
/*
The table to store mapping of product id to categories.
*/
CREATE table PRODUCT_CATEGORY
( 	
	PRODUCT_ID INTEGER(8) UNSIGNED NOT NULL,
	CATEGORY_ID INTEGER(8) NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,	
	
	PRIMARY KEY USING BTREE (PRODUCT_ID, CATEGORY_ID)			
) ENGINE=InnoDB;
describe PRODUCT_CATEGORY;

ALTER TABLE PRODUCT_CATEGORY ADD INDEX CATEGORY_ID_idx using BTREE (CATEGORY_ID) 