drop table RETAILER;
CREATE table RETAILER
( 
	RETAILER_ID VARCHAR(20) NOT NULL,
	RETAILER_NAME VARCHAR(20) NOT NULL,
	URL VARCHAR(500) NOT NULL,
	LOGO BLOB,
	TIME_MODIFIED DATETIME NOT NULL,

	PRIMARY KEY USING HASH (RETAILER_ID)
) ENGINE=InnoDB;
describe retailer;