DROP TABLE SPHX_INDEX_COUNTER;
CREATE TABLE SPHX_INDEX_COUNTER
(
    INDEX_ID INTEGER PRIMARY KEY NOT NULL,
    MAX_MAIN_IDX_ID INTEGER NOT NULL,
    TIME_MODIFIED DATETIME NOT NULL
) ENGINE=InnoDB;
DESCRIBE SPHX_INDEX_COUNTER;
