drop table CATEGORY;
CREATE table CATEGORY
( 
	CATEGORY_ID INTEGER AUTO_INCREMENT,
	CATEGORY_NAME VARCHAR(100) NOT NULL,
	GENERIC_CATEGORY_ID VARCHAR(100) NOT NULL,
	PARENT_CATEGORY_ID VARCHAR(100) NOT NULL,
	RETAILER_ID VARCHAR(20) NOT NULL,
	CATEGORY_FETCH_RULE_ID VARCHAR(20),
	URL VARCHAR(500),
	ACTIVE  CHAR(1) NOT NULL,
	PARENT CHAR(1) NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,

	PRIMARY KEY USING HASH (CATEGORY_ID, RETAILER_ID),
	INDEX GENERIC_CATEGORY_ID_idx using BTREE (GENERIC_CATEGORY_ID),
	INDEX PARENT_CATEGORY_ID_idx using BTREE (PARENT_CATEGORY_ID),
	INDEX RETAILER_ID_idx using BTREE (RETAILER_ID)
	
);
describe CATEGORY;
