use PRODUCTS
drop procedure UpdateProduct;
DELIMITER // 
create procedure UpdateProduct(	
	IN IN_PRODUCT_NAME VARCHAR(200),
	IN IN_CATEGORY_ID VARCHAR(100),
	IN IN_RETAILER_ID VARCHAR(20),
	IN IN_MODEL_NO VARCHAR(100),					
	IN IN_DESCRIPTION VARCHAR(5000),	
	IN IN_IMAGE_URL VARCHAR(500),
	IN IN_START_DATE DATETIME,	
	IN IN_URL VARCHAR(500),
	IN IN_ACTIVE CHAR(1),
	IN IN_TIME_MODIFIED DATETIME,
	IN IN_DATE DATE,
	IN IN_PRICE FLOAT,
	OUT RESULT NUMERIC
)
begin
DECLARE last_update_date DATE;
DECLARE last_price FLOAT DEFAULT 0;
DECLARE product_count INT DEFAULT 1;
SET RESULT = 2;
SELECT count(*) INTO product_count FROM PRODUCT WHERE PRODUCT_NAME=IN_PRODUCT_NAME AND CATEGORY_ID=IN_CATEGORY_ID AND RETAILER_ID=IN_RETAILER_ID; 
IF product_count = 0 THEN
	INSERT INTO PRODUCT (PRODUCT_NAME, CATEGORY_ID, RETAILER_ID, MODEL_NO, DESCRIPTION, IMAGE_URL, START_DATE, URL, ACTIVE, TIME_MODIFIED) values ( IN_PRODUCT_NAME, IN_CATEGORY_ID, IN_RETAILER_ID, IN_MODEL_NO, IN_DESCRIPTION, IN_IMAGE_URL, IN_START_DATE, IN_URL, IN_ACTIVE, IN_TIME_MODIFIED );
	INSERT INTO PRODUCT_PRICE_HISTORY (PRODUCT_NAME, CATEGORY_ID, RETAILER_ID, PRICE, DATE) values (IN_PRODUCT_NAME, IN_CATEGORY_ID, IN_RETAILER_ID, IN_PRICE, IN_DATE);
	SET RESULT = 0;
ELSE
	UPDATE PRODUCT set MODEL_NO=IN_MODEL_NO, DESCRIPTION=IN_DESCRIPTION, IMAGE_URL=IN_IMAGE_URL, URL=IN_URL, TIME_MODIFIED=IN_TIME_MODIFIED
	WHERE PRODUCT_NAME=IN_PRODUCT_NAME AND CATEGORY_ID=IN_CATEGORY_ID AND RETAILER_ID=IN_RETAILER_ID;
		
	SELECT PRICE INTO last_price FROM PRODUCT_PRICE_HISTORY WHERE CATEGORY_ID=IN_CATEGORY_ID AND PRODUCT_NAME=IN_PRODUCT_NAME AND RETAILER_ID=IN_RETAILER_ID AND DATE=(SELECT MAX(DATE) FROM PRODUCT_PRICE_HISTORY WHERE PRODUCT_NAME=IN_PRODUCT_NAME AND CATEGORY_ID=IN_CATEGORY_ID AND RETAILER_ID=IN_RETAILER_ID);
	IF (last_price != IN_PRICE) THEN
		INSERT INTO PRODUCT_PRICE_HISTORY (PRODUCT_NAME, CATEGORY_ID, RETAILER_ID, DATE, PRICE) VALUES (IN_PRODUCT_NAME, IN_CATEGORY_ID, IN_RETAILER_ID, IN_DATE, IN_PRICE); 
	END IF;
end if;
end//
DELIMITER ;