use PRODUCTS;
drop procedure UpdateCategory;
DELIMITER // 
delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `UpdateCategory`(

IN IN_CATEGORY_NAME VARCHAR(100),
IN IN_PARENT_CATEGORY_ID NUMERIC,
IN IN_PARENT_CATEGORY_NAME VARCHAR(100),
IN IN_RETAILER_ID VARCHAR(20),
IN IN_URL VARCHAR(500),
IN IN_ACTIVE  CHAR(1),
IN IN_PARENT  CHAR(1),
IN IN_TIME_MODIFIED DATETIME,
IN IN_EXT_ID VARCHAR(100),
OUT OUT_RESULT NUMERIC,
OUT OUT_CATEGORY_ID NUMERIC
)
begin
SET OUT_RESULT = 2;
    
    
    set @category_exists = (select count(*) from CATEGORY where CATEGORY_NAME=IN_CATEGORY_NAME and PARENT_CATEGORY_NAME=IN_PARENT_CATEGORY_NAME and RETAILER_ID = IN_RETAILER_ID);
    if not(@category_exists) then
        INSERT into CATEGORY ( CATEGORY_NAME, PARENT_CATEGORY_ID, PARENT_CATEGORY_NAME, RETAILER_ID, URL, ACTIVE, PARENT, TIME_MODIFIED, EXT_ID )
        values( IN_CATEGORY_NAME, IN_PARENT_CATEGORY_ID, IN_PARENT_CATEGORY_NAME, IN_RETAILER_ID, IN_URL, IN_ACTIVE, IN_PARENT, IN_TIME_MODIFIED, IN_EXT_ID );
        SET OUT_RESULT = 0;
else
        
        set @has_key_information_not_changed = (select count(*) from CATEGORY where CATEGORY_NAME=IN_CATEGORY_NAME and PARENT_CATEGORY_NAME=IN_PARENT_CATEGORY_NAME and RETAILER_ID = IN_RETAILER_ID and PARENT=IN_PARENT and ACTIVE=IN_ACTIVE and URL=IN_URL);
        if not(@has_key_information_not_changed) then
            INSERT INTO CATEGORY_HISTORY SELECT CATEGORY_ID, CATEGORY_NAME, GENERIC_CATEGORY_ID, GENERIC_CATEGORY_NAME, PARENT_CATEGORY_ID, PARENT_CATEGORY_NAME, RETAILER_ID, URL, ACTIVE, PARENT, TIME_MODIFIED, EXT_ID 
            from CATEGORY where CATEGORY_NAME=IN_CATEGORY_NAME and PARENT_CATEGORY_ID=IN_PARENT_CATEGORY_ID and RETAILER_ID=IN_RETAILER_ID;
            UPDATE CATEGORY set PARENT_CATEGORY_ID=IN_PARENT_CATEGORY_ID, URL=IN_URL, ACTIVE=IN_ACTIVE,PARENT=IN_PARENT, TIME_MODIFIED=IN_TIME_MODIFIED, EXT_ID = IN_EXT_ID where CATEGORY_NAME=IN_CATEGORY_NAME and PARENT_CATEGORY_ID=IN_PARENT_CATEGORY_ID and RETAILER_ID=IN_RETAILER_ID;
            SET OUT_RESULT = 1;
        end if;
        
        UPDATE CATEGORY set PARENT_CATEGORY_ID=IN_PARENT_CATEGORY_ID, URL=IN_URL, ACTIVE=IN_ACTIVE,PARENT=IN_PARENT, TIME_MODIFIED=IN_TIME_MODIFIED, EXT_ID = IN_EXT_ID where CATEGORY_NAME=IN_CATEGORY_NAME and PARENT_CATEGORY_NAME=IN_PARENT_CATEGORY_NAME and RETAILER_ID=IN_RETAILER_ID;
    end if;
    SET OUT_CATEGORY_ID = (SELECT CATEGORY_ID from CATEGORY where CATEGORY_NAME=IN_CATEGORY_NAME and PARENT_CATEGORY_NAME=IN_PARENT_CATEGORY_NAME and RETAILER_ID = IN_RETAILER_ID);  
end$$

