USE PRODUCTS
DROP TABLE IF EXISTS CATEGORY_PARSE_ERR;

CREATE table CATEGORY_PARSE_ERR
( 	
	RETAILER_ID VARCHAR(20) NOT NULL,
	CATEGORY_ID INTEGER(8) UNSIGNED NOT NULL,
	CATEGORY_NAME VARCHAR(300) NOT NULL,			
	RECORD_TIME DATETIME NOT NULL,
	TYPE VARCHAR(16) NOT NULL,
	TEXT VARCHAR(300)		
) ENGINE=InnoDB;
describe CATEGORY_PARSE_ERR;