drop table CATEGORY_HISTORY;
CREATE table CATEGORY_HISTORY
( 
	CATEGORY_ID INTEGER,
	CATEGORY_NAME VARCHAR(100) NOT NULL,
	GENERIC_CATEGORY_ID INT,
	GENERIC_CATEGORY_NAME VARCHAR(100),
	PARENT_CATEGORY_ID INTEGER NOT NULL,
	PARENT_CATEGORY_NAME VARCHAR(100) NOT NULL,
	RETAILER_ID VARCHAR(20) NOT NULL,
	URL VARCHAR(500),
	ACTIVE  CHAR(1) NOT NULL,
	PARENT CHAR(1) NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,
	EXT_ID VARCHAR(100) NULL,

	INDEX CATEGORY_RETAILER_idx USING HASH (CATEGORY_ID, RETAILER_ID),
	INDEX GENERIC_CATEGORY_ID_idx using BTREE (GENERIC_CATEGORY_ID),
	INDEX PARENT_CATEGORY_ID_idx using BTREE (PARENT_CATEGORY_ID),
	INDEX RETAILER_ID_idx using BTREE (RETAILER_ID)
) ENGINE=InnoDB;
describe CATEGORY_HISTORY;

#ALTER TABLE CATEGORY_HISTORY CHANGE COLUMN PARENT_CATEGORY_ID PARENT_CATEGORY_NAME VARCHAR(100) NOT NULL; 
#ALTER TABLE CATEGORY_HISTORY ADD COLUMN PARENT_CATEGORY_ID INTEGER NOT NULL AFTER GENERIC_CATEGORY_ID;
#ALTER TABLE CATEGORY_HISTORY CHANGE COLUMN GENERIC_CATEGORY_ID GENERIC_CATEGORY_NAME VARCHAR(100); 
#ALTER TABLE CATEGORY_HISTORY ADD COLUMN GENERIC_CATEGORY_ID INTEGER NULL AFTER CATEGORY_NAME;
#ALTER TABLE CATEGORY_HISTORY DROP COLUMN CATEGORY_FETCH_RULE_ID;
#ALTER TABLE CATEGORY_HISTORY ADD COLUMN EXT_ID VARCHAR(100) NULL;
