use PRODUCTS
drop table DAILY_TASKS_LOCK;
CREATE table DAILY_TASKS_LOCK
(
	 TASK_NAME VARCHAR(50) NOT NULL,
	 TASK_ID INT NOT NULL,
	 ATTEMPT INT NOT NULL,
	 DATE DATE NOT NULL,
	 LOCK_TIME DATETIME NOT NULL,	 	
	 START_TIME DATETIME,	 
	 END_TIME DATETIME,
	 ERR_TIME DATETIME,
	 PRIMARY KEY USING BTREE (TASK_NAME, TASK_ID, ATTEMPT, DATE)
) ENGINE=InnoDB;
describe DAILY_TASKS_LOCK;