use PRODUCTS;
DROP TABLE IF EXISTS DAILY_PRICE_MOVEMENT_SUMMARY;
CREATE TABLE `DAILY_PRICE_MOVEMENT_SUMMARY` (
   CALENDAR_DATE DATETIME  NULL,			
   PRODUCT_ID INTEGER(8) UNSIGNED NOT NULL,
   LATEST_PRICE FLOAT,
   LATEST_PRICE_TIME DATETIME,
   LAST_PRICE FLOAT,
   LAST_PRICE_TIME DATETIME,
   MAX_PRICE FLOAT,
   MAX_PRICE_TIME DATETIME,
   AVERAGE_PRICE FLOAT,
   IS_PRICE_DROP VARCHAR(10),
   TIME_MODIFIED DATETIME NOT NULL,
   PRIMARY KEY USING BTREE ( PRODUCT_ID),
   INDEX TIME_MODIFIED_idx using BTREE (TIME_MODIFIED),
   INDEX LAST_PRICE_TIME_idx using BTREE (LAST_PRICE_TIME)
) ENGINE=MyISAM;


#ALTER TABLE DAILY_PRICE_MOVEMENT_SUMMARY ADD COLUMN TIME_MODIFIED DATETIME NOT NULL DEFAULT '2012-01-01 00.00.00.000'
#ALTER TABLE DAILY_PRICE_MOVEMENT_SUMMARY ADD INDEX TIME_MODIFIED_idx using BTREE (TIME_MODIFIED)