use PRODUCTS;
DROP TABLE IF EXISTS PERFORMANCE_METRIC;
CREATE TABLE `PERFORMANCE_METRIC` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `PERIOD` varchar(20) NOT NULL,
  `TOTAL_PROCESS_TIME` int(11) DEFAULT '0',
  `TOTAL_PROCESS_COUNT` int(11) DEFAULT '0',
  `TOTAL_SUCCESS_COUNT` int(11) DEFAULT '0',
  `TOTAL_FAILURE_COUNT` int(11) DEFAULT '0',
  `MAX_PROCESS_TIME` int(11) DEFAULT '0',
  `MIN_PROCESS_TIME` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `NAME_ID_idx` (`NAME`) USING BTREE,
  KEY `PERIOD_idx` (`PERIOD`) USING BTREE,
  KEY `NAME_PERIOD_idx` (`NAME`,`PERIOD`)
) ENGINE=InnoDB;


