USE PRODUCTS;
DROP TABLE IF EXISTS PRICE_ALERT;

CREATE TABLE PRICE_ALERT
(
	ALERT_ID INTEGER(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	EMAIL_ID VARCHAR(256) NOT NULL,
	PRODUCT_ID INTEGER(8) UNSIGNED NOT NULL,
	ALERT_PRICE FLOAT NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,
	ALERT_START_TIME DATETIME NOT NULL,
	ALERT_END_TIME DATETIME NOT NULL,
	ALERT_TYPE VARCHAR(100) NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	
	PRIMARY KEY USING BTREE (ALERT_ID),
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID)
) ENGINE=MYISAM;
describe PRICE_ALERT;