use PRODUCTS;

CREATE table PRODUCT_SELL_RANKS_HISTORY_STALE
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	RANK DECIMAL(8) NOT NULL,
	END_TIME DATETIME,
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID),
) ENGINE=MYISAM;
describe PRODUCT_SELL_RANKS_HISTORY_STALE;

--ALTER TABLE PRODUCT_SELL_RANKS_HISTORY_STALE ADD COLUMN RETAILER_ID_NUM int(4) DEFAULT NULL