use PRODUCTS;

CREATE table PRODUCT_REVIEWS_HISTORY_STALE
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	RATING DECIMAL(4,2) NOT NULL,
	NUM_REVIEWS DECIMAL(6) NOT NULL,		
	END_TIME DATETIME, 
	TIME_MODIFIED DATETIME NOT NULL,
	RETAILER_ID_NUM int(4) DEFAULT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID),
	INDEX TIME_idx using BTREE (TIME)
) ENGINE=MYISAM;
describe PRODUCT_REVIEWS_HISTORY_STALE;	

--ALTER TABLE PRODUCT_REVIEWS_HISTORY_STALE ADD COLUMN RETAILER_ID_NUM int(4) DEFAULT NULL