USE PRODUCTS;

CREATE table PRODUCT_SUMMARY_STALE
( 	
	PRODUCT_ID INTEGER(8) UNSIGNED NOT NULL,
	RETAILER_ID VARCHAR(20) NOT NULL,
	PRODUCT_NAME VARCHAR(300) NOT NULL,
	MODEL_NO VARCHAR(100),
	IMAGE_URL VARCHAR(500) NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME,
	URL VARCHAR(500) NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,		
	LAST_DOWNLOAD_TIME DATETIME NOT NULL,
	PRICE FLOAT NOT NULL,	
	REVIEW_RATING DECIMAL(4,2) NOT NULL DEFAULT -1,
	NUM_REVIEWS DECIMAL(6) NOT NULL DEFAULT -1,
	BEST_SELLER_RANK DECIMAL(8) NOT NULL DEFAULT -1,
	UID VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(5),
	PRIMARY KEY USING BTREE (PRODUCT_ID),			
	INDEX RETAILER_ID_idx using BTREE (RETAILER_ID),
	INDEX TIME_MODIFIED_idx using BTREE (TIME_MODIFIED)
) ENGINE=MYISAM;
describe PRODUCT_SUMMARY_STALE;
