USE PRODUCTS

CREATE table PRODUCT_SUMMARY
( 	
	PRODUCT_ID INTEGER(8) UNSIGNED NOT NULL,
	UID VARCHAR(100) NOT NULL,
	RETAILER_ID VARCHAR(20) NOT NULL,
	PRODUCT_NAME VARCHAR(300) NOT NULL,
	PRICE FLOAT NOT NULL,	
	REVIEW_RATING DECIMAL(4,2) NOT NULL DEFAULT -1,
	NUM_REVIEWS DECIMAL(6) NOT NULL DEFAULT -1,
	BEST_SELLER_RANK DECIMAL(8) NOT NULL DEFAULT -1,
	MODEL_NO VARCHAR(100),
	DESCRIPTION VARCHAR(5),
	IMAGE_URL VARCHAR(500) NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME,
	URL VARCHAR(500) NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	LAST_DOWNLOAD_TIME DATETIME NOT NULL,
	TIME_MODIFIED DATETIME NOT NULL,		
	PRIMARY KEY USING BTREE (PRODUCT_ID),			
	INDEX RETAILER_ID_idx using BTREE (RETAILER_ID),
	INDEX TIME_MODIFIED_idx using BTREE (TIME_MODIFIED),
	INDEX UID_idx USING BTREE (UID),
	CONSTRAINT UNIQUE KEY UNIQ_UID_RETAILER_KEY USING BTREE (UID, RETAILER_ID)
) ENGINE=MYISAM;
describe PRODUCT_SUMMARY;

#alter table PRODUCT_SUMMARY ADD COLUMN REVIEW_RATING DECIMAL(4,2), ADD COLUMN NUM_REVIEWS DECIMAL(6) NOT NULL DEFAULT -1, ADD COLUMN BEST_SELLER_RANK DECIMAL(8) NOT NULL DEFAULT -1;
#alter table PRODUCT_SUMMARY ADD COLUMN `UID` varchar(100) NOT NULL DEFAULT "",
#alter table PRODUCT_SUMMARY ADD INDEX TIME_MODIFIED_idx using BTREE (TIME_MODIFIED)
#alter table PRODUCT_SUMMARY DROP INDEX PRODUCT_NAME_idx
alter table PRODUCT_SUMMARY ADD CONSTRAINT UNIQUE KEY UNIQ_UID_RETAILER_KEY USING BTREE (UID, RETAILER_ID)
alter table PRODUCT_SUMMARY ADD INDEX UID_idx USING BTREE (UID) 

select UID, count(*) from PRODUCT_SUMMARY where ACTIVE='1' group by UID having count(*) > 1