USE PRODUCTS
DROP TABLE IF EXISTS PRODUCT_SUMMARY_PAGE;
/*
The table stores the html page information for product summary page
*/
CREATE table PRODUCT_SUMMARY_PAGE
( 	
	PRODUCT_NAME VARCHAR(300) NOT NULL,
	PRODUCT_SUMMARY_PAGE_ID INTEGER NOT NULL,
	DOWNLOAD_TIME DATETIME NOT NULL,
	INDEX PRODUCT_NAME_DOWNLOAD_TIME_idx using BTREE (PRODUCT_NAME, DOWNLOAD_TIME)	
) ENGINE=InnoDB;
describe PRODUCT_SUMMARY_PAGE;