use PRODUCTS

CREATE table PRODUCT_PRICES_HISTORY
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	PRICE FLOAT NOT NULL,		
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID),
) ENGINE=MYISAM;
describe PRODUCT_PRICES_HISTORY;

#ALTER TABLE PRODUCT_PRICES_HISTORY DROP COLUMN RETAILER_ID;

CREATE table PRODUCT_PRICES_HISTORY_1
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	PRICE FLOAT NOT NULL,		
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID)
) ENGINE=MYISAM;
describe PRODUCT_PRICES_HISTORY_1;

CREATE table PRODUCT_PRICES_HISTORY_2
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	PRICE FLOAT NOT NULL,		
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID)
) ENGINE=MYISAM;
describe PRODUCT_PRICES_HISTORY_2;

CREATE table PRODUCT_PRICES_HISTORY_3
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	PRICE FLOAT NOT NULL,		
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID)
) ENGINE=MYISAM;
describe PRODUCT_PRICES_HISTORY_3;

CREATE table PRODUCT_PRICES_HISTORY_4
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	PRICE FLOAT NOT NULL,		
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID)
) ENGINE=MYISAM;
describe PRODUCT_PRICES_HISTORY_4;

CREATE table PRODUCT_PRICES_HISTORY_5
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	PRICE FLOAT NOT NULL,		
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID)
) ENGINE=MYISAM;
describe PRODUCT_PRICES_HISTORY_5;

CREATE table PRODUCT_PRICES_HISTORY_6
( 
	PRODUCT_ID INTEGER(8) NOT NULL,	
	TIME DATETIME NOT NULL,	
	PRICE FLOAT NOT NULL,		
	TIME_MODIFIED DATETIME NOT NULL,
	INDEX PRODUCT_ID_idx using BTREE (PRODUCT_ID)
) ENGINE=MYISAM;
describe PRODUCT_PRICES_HISTORY_6;


#INSERT INTO PRODUCT_PRICES_HISTORY_1 select A.PRODUCT_ID, A.TIME, A.PRICE, A.TIME_MODIFIED from PRODUCT_PRICES_HISTORY A, PRODUCT_SUMMARY B WHERE A.PRODUCT_ID = B.PRODUCT_ID and B.RETAILER_ID IN ( "bananarepublic", "bjs", "bestbuy", "costco", "cvs", "gap", "homedepot", "jcpenny" );
#INSERT INTO PRODUCT_PRICES_HISTORY_2 select A.PRODUCT_ID, A.TIME, A.PRICE, A.TIME_MODIFIED from PRODUCT_PRICES_HISTORY A, PRODUCT_SUMMARY B WHERE A.PRODUCT_ID = B.PRODUCT_ID and B.RETAILER_ID IN ( "kohls", "lowes", "macys", "nordstrom", "oldnavy", "riteaid", "sears", "samsclub", "staples", "walgreens" );
#INSERT INTO PRODUCT_PRICES_HISTORY_3 select A.PRODUCT_ID, A.TIME, A.PRICE, A.TIME_MODIFIED from PRODUCT_PRICES_HISTORY A, PRODUCT_SUMMARY B WHERE A.PRODUCT_ID = B.PRODUCT_ID and B.RETAILER_ID IN ( "walmart" );
#INSERT INTO PRODUCT_PRICES_HISTORY_4 select A.PRODUCT_ID, A.TIME, A.PRICE, A.TIME_MODIFIED from PRODUCT_PRICES_HISTORY A, PRODUCT_SUMMARY B WHERE A.PRODUCT_ID = B.PRODUCT_ID and B.RETAILER_ID IN ( "target" );
#INSERT INTO PRODUCT_PRICES_HISTORY_5 select A.PRODUCT_ID, A.TIME, A.PRICE, A.TIME_MODIFIED from PRODUCT_PRICES_HISTORY A, PRODUCT_SUMMARY B WHERE A.PRODUCT_ID = B.PRODUCT_ID and B.RETAILER_ID IN ( "amazon", "amazonbs" );
#INSERT INTO PRODUCT_PRICES_HISTORY_6 select A.PRODUCT_ID, A.TIME, A.PRICE, A.TIME_MODIFIED from PRODUCT_PRICES_HISTORY A, PRODUCT_SUMMARY B WHERE A.PRODUCT_ID = B.PRODUCT_ID and B.RETAILER_ID IN ( "babysrus", "toysrus" );


#RENAME TABLE PRODUCT_PRICES_HISTORY TO PRODUCT_PRICES_HISTORY_BACKUP_20130713;
#RENAME TABLE PRODUCT_PRICES_HISTORY_NEW TO PRODUCT_PRICES_HISTORY;



