/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.genereated.pricealert;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PRICE_ALERT_ERROR_CODE implements org.apache.thrift.TEnum {
  SYSTEM_ERROR(0),
  DUPLICATE_PRICE_ALERT_ON_PRODUCTID(1),
  INVALID_ALERTID(2);

  private final int value;

  private PRICE_ALERT_ERROR_CODE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PRICE_ALERT_ERROR_CODE findByValue(int value) { 
    switch (value) {
      case 0:
        return SYSTEM_ERROR;
      case 1:
        return DUPLICATE_PRICE_ALERT_ON_PRODUCTID;
      case 2:
        return INVALID_ALERTID;
      default:
        return null;
    }
  }
}
