/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.genereated.pricealert;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PriceAlertTypeThrift implements org.apache.thrift.TEnum {
  ALERT_WHEN_AT_PRICE(0),
  ALERT_WHEN_PRICE_DROPS(1);

  private final int value;

  private PriceAlertTypeThrift(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PriceAlertTypeThrift findByValue(int value) { 
    switch (value) {
      case 0:
        return ALERT_WHEN_AT_PRICE;
      case 1:
        return ALERT_WHEN_PRICE_DROPS;
      default:
        return null;
    }
  }
}
